apiVersion: v1
kind: PersistentVolume
metadata:
 name: block-pv
spec:
 storageClassName: manual
 capacity: 
  storage: 10Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /home/mittal_sonal04/pvlabs
